version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-container-local
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33006:3306"

volumes:
  mysql_data:
    external: true