version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-container-1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-default_root_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - spring-application

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: spring-application
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default_spring_profile}
    ports:
      - "8080:8080"
    networks:
      - spring-application

networks:
  spring-application:
    driver: bridge

volumes:
  mysql_data:
    external: true